# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-xml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-executables-have-shebangs
    -   id: check-byte-order-marker
    -   id: check-ast

    # Ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
    -   id: ruff
        args: ["--config", "./.ruff.toml"]

    # Mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        #args: [--strict, --ignore-missing-imports, --disable-error-code=attr-defined, --disable-error-code=index, --no-warn-unused-ignores]
        args: ["--config-file", "./.mypy.ini"]

    # pytest
#-   repo: local
#    hooks:
#    -   id: pytest
#        name: pytest
#        entry: pytest ./tests --config-file=./pytest.ini
#        language: system
#        pass_filenames: false
#        always_run: true
